# [START reportloader service]
---
  kind: Service
  apiVersion: v1
  metadata:
    name: reportloader
    namespace: tw-reporter
  spec:
    type: NodePort
    selector:
      app: reportloader
    ports:
      - protocol: TCP
        port: 5552
        targetPort: 5552
        name: reportloader
# [END reportloader service]        