version: '3'
services:
#  mysqltomongo:
#    build:
#      context: .
#      dockerfile: dockerfiles/mysqltomongo
#    environment:
#       - MONGO_HOST=mongodb       
#    links:
#      - "mongodb"
#    depends_on:
#      - mongodb
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"   
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=DKdkSM*$$*12012009

  reportloader:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
    build:
      context: .
      dockerfile: dockerfiles/reportloader
    environment:
      - MONGO_HOST=mongodb
##    volumes:
##      - ./reportloader:/usr/src/report-loader/reportloader     
    ports:
       - 5552:5552      
    links:
      - "mongodb"
    depends_on:
      - mongodb
      
  mongodb:
    build:
      context: .
      dockerfile: dockerfiles/mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
      - ./data/dump:/data/dump
    ports:
       - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet